import = ["~/.config/alacritty/themes/themes/everforest_dark.toml"]

[window]
decorations = "None"
padding = { y = 0, x = 0 }

[font]
size = 15
normal = { family = "Iosevka NFP", style = "Regular" }

[bell]
duration = 0
