import = ["~/.config/alacritty/themes/themes/solarized_light.toml"]

[window]
decorations = "Buttonless"
dynamic_padding = true
padding = { x = 10, y = 8 }

[font]
size = 14
normal = { family = "Input Mono Condensed", style = "Regular" }

[bell]
duration = 0
