import = ["~/.config/alacritty/theme.toml"]

[window]
decorations = "Buttonless"
padding = { y = 4, x = 4 }

[font]
size = 15
normal = { family = "Iosevka NFP", style = "Regular" }

[bell]
duration = 0
