import = ["~/.config/alacritty/themes/themes/solarized_light.toml"]

[window]
decorations = "Buttonless"
padding = { y = 12, x = 4 }

[font]
size = 16
normal = { family = "Iosevka NFP", style = "Regular" }

[bell]
duration = 0
