import = ["~/.config/alacritty/themes/themes/everforest_light.toml"]

[window]
decorations = "Buttonless"

[font]
size = 16
normal = { family = "Iosevka NFP", style = "Regular" }

[bell]
duration = 0
