import = ["~/.config/alacritty/themes/themes/solarized_light.toml"]

[window]
decorations = "Buttonless"
dynamic_padding = true
padding = { x = 10, y = 8 }

[font]
size = 16
normal = { family = "ZedMono Nerd Font Mono", style = "Regular" }

[bell]
duration = 0
