# Homebrew stuff
tap "rcmdnk/file"
tap "homebrew/bundle"
tap "homebrew/services"
brew "brew-file"

# Fonts
brew "font-input"

# Applications
cask "alacritty"
cask "1password"
cask "1password-cli"
mas "tailscale", id: 1475387142
cask "raycast"
cask "rectangle"
cask "google-chrome"
cask "firefox"
cask "obsidian"
cask "todoist"
cask "spotify"
cask "slack"
cask "discord"
cask "signal"
cask "zoom"
cask "loom"
cask "sketch"
cask "figma"
cask "gimp"
cask "elgato-camera-hub"
cask "autodesk-fusion"
cask "visual-studio-code"
cask "zed"

# Programming
brew "tmux"
brew "tmuxp"
brew "asdf"
brew "ansible"
brew "deno"
brew "go"
brew "colima"
brew "docker"
brew "docker-compose"
brew "docker-buildx"
tap "int128/kubelogin"
brew "int128/kubelogin/kubelogin"

# Tools
brew "zsh"
brew "vim"
brew "gnupg"
brew "sops"
brew "git"
brew "git-crypt"
brew "git-delta"
brew "fzf"
brew "ripgrep"
brew "watch"
brew "curl"
brew "wget"
brew "httpie"
brew "nmap"
brew "bat"
brew "fd"
brew "jq"
brew "yq"
brew "tree"
brew "direnv"
brew "unar"
cask "ngrok"
brew "m-cli"
brew "pandoc"
brew "imagemagick"
brew "ffmpeg"
brew "oath-toolkit"
brew "openconnect"

# TUIs
brew "k9s"
brew "lazydocker"
brew "lazygit"

# Service Utils
brew "awscli"
brew "aws-vault"
tap "superfly/tap"
brew "superfly/tap/flyctl"
tap "github/gh"
brew "gh"
brew "glab"
brew "mas"

# Libs
brew "yubikey-personalization"
brew "libssh2"
tap "filosottile/musl-cross"
brew "filosottile/musl-cross/musl-cross"
