# Homebrew stuff
tap "rcmdnk/file"
tap "homebrew/bundle"
tap "homebrew/services"
brew "brew-file"

# Applications
cask "iterm2"
cask "1password"
cask "1password-cli"
mas "tailscale", id: 1475387142
cask "raycast"
cask "rectangle"
cask "alex313031-thorium"
cask "firefox"
cask "obsidian"
cask "todoist"
cask "spotify"
cask "slack"
cask "discord"
cask "signal"
cask "zoom"
cask "loom"
cask "sketch"
cask "figma"
cask "gimp"
cask "elgato-camera-hub"
cask "autodesk-fusion"

# Editors
cask "visual-studio-code"
cask "zed"
brew "neovim"

# Programming
brew "asdf"
brew "ansible"
brew "go"
brew "openjdk"
brew "postgresql@14"
brew "redis"
brew "mysql"
brew "pyenv"
brew "python@3.9"
brew "poetry"
brew "pyenv"
brew "rbenv"
brew "php"
brew "rustup-init"
brew "rust-analyzer"
brew "deno"
tap "hashicorp/tap"
brew "tfenv"

# Containers
brew "colima"
brew "docker"
brew "docker-compose"
brew "docker-buildx"
brew "helm"
brew "helmfile"
tap "int128/kubelogin"
brew "int128/kubelogin/kubelogin"

# Tools
brew "zsh"
brew "vim"
brew "gnupg"
brew "sops"
brew "git"
brew "git-crypt"
brew "git-delta"
brew "fzf"
brew "ripgrep"
brew "watch"
brew "curl"
brew "wget"
brew "httpie"
brew "nmap"
brew "bat"
brew "fd"
brew "jq"
brew "yq"
brew "tree"
brew "direnv"
brew "unar"
cask "ngrok"
brew "m-cli"
brew "pandoc"
brew "imagemagick"
brew "ffmpeg"
brew "oath-toolkit"
brew "openconnect"

# TUIs
brew "tmux"
brew "tmuxinator"
tap "cjbassi/ytop"
brew "cjbassi/ytop/ytop"
brew "k9s"
brew "lazydocker"
brew "lazygit"

# Service Utils
brew "awscli"
brew "aws-vault"
tap "superfly/tap"
brew "superfly/tap/flyctl"
tap "github/gh"
brew "gh"
brew "glab"
brew "mas"

# Fonts
tap "homebrew/cask-fonts"
cask "font-iosevka-nerd-font"

# Libs
brew "yubikey-personalization"
brew "libssh2"
tap "filosottile/musl-cross"
brew "filosottile/musl-cross/musl-cross"