# Homebrew stuff
tap "rcmdnk/file"
tap "homebrew/bundle"
tap "homebrew/services"
brew "brew-file"

# Fonts
cask "font-fira-code-nerd-font"

# Applications
cask "iterm2"
cask "ghostty"
cask "1password"
cask "1password-cli"
cask "audacity"
mas "tailscale", id: 1475387142
cask "raycast"
cask "rectangle"
cask "meetingbar"
cask "firefox"
brew "firefoxpwa"
cask "obsidian"
cask "todoist"
cask "spotify"
cask "slack"
cask "zoom"
cask "loom"
cask "gimp"
cask "visual-studio-code"
cask "cursor"
cask "chatgpt"
cask "zed"
brew "neovim"

# Programming
brew "tmux"
brew "tmuxp"
brew "mise"
brew "ansible"
brew "node"
brew "oven-sh/bun/bun"
brew "go"
brew "rust"
brew "colima"
brew "docker"
brew "docker-compose"
brew "docker-buildx"
tap "int128/kubelogin"
brew "int128/kubelogin/kubelogin"
tap "hashicorp/tap"
brew "hashicorp/tap/vault"

# Tools
brew "zsh"
brew "vim"
brew "gnupg"
brew "sops"
brew "git"
brew "git-crypt"
brew "git-delta"
brew "fzf"
brew "lsd"
brew "ripgrep"
brew "watch"
brew "curl"
brew "wget"
brew "httpie"
brew "aichat"
brew "nmap"
brew "bat"
brew "fd"
brew "jq"
brew "yq"
brew "tree"
brew "direnv"
brew "bruno-cli"
brew "unar"
cask "ngrok"
brew "pandoc"
brew "imagemagick"
brew "ffmpeg"
brew "oath-toolkit"
brew "openconnect"

# TUIs
brew "btop"
brew "k9s"
brew "lazydocker"
brew "lazygit"

# Service Utils
brew "awscli"
brew "aws-vault"
brew "flyctl"
brew "b2-tools"
brew "tea"
brew "gh"
brew "glab"
brew "mas"

# Libs
brew "yubikey-personalization"
brew "libssh2"
tap "filosottile/musl-cross"
brew "filosottile/musl-cross/musl-cross"
