- name: get-obsidian-configs
  ansible.builtin.shell: "ls {{ dotfiles_dir }}/obsidian/"
  register: obsidian_configs

- name: check-obsidian-vault
  stat:
      path: "{{ obsidian_dir }}/brain"
  register: obsidian_vault_dir

- name: link-obsidian-vault
  ansible.builtin.file:
      src: "{{ dotfiles_dir }}/obsidian/{{ item }}"
      dest: "{{ obsidian_dir }}/brain/.obsidian/{{ item }}"
      state: link
      force: true
  with_items: "{{ obsidian_configs.stdout_lines }}"
  when: obsidian_vault_dir.stat.exists
