if &compatible
  set nocompatible
endif

nnoremap ; :

syntax on
filetype plugin indent on
runtime macros/matchit.vim

set shiftwidth=2
set softtabstop=2
set tabstop=2
set autoindent
set expandtab

set relativenumber
set number
set ruler
set showcmd

set showmatch
set hidden
set nowrap

set hlsearch
set incsearch
set ignorecase
set smartcase

set esckeys " allows function keys to be recognized in insert mode
set ttimeoutlen=20
set timeoutlen=1000

augroup languages
  autocmd!
  autocmd FileType markdown,text set wrap linebreak nolist
augroup END
" if &filetype == "" || &filetype == "markdown" || &filetype == "text"
"   set wrap
"   set linebreak
"   set nolist
" endif
