if &compatible
  set nocompatible
endif

filetype plugin indent on
syntax on

set relativenumber
set number
set shiftwidth=2
set tabstop=2
set expandtab
set hidden
set nowrap

if &filetype == "" || &filetype == "markdown" || &filetype == "text"
  set wrap
  set linebreak
  set nolist
endif
