- name: link-lazygit-config
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/lazygit.yml"
    dest: "{{ home_dir }}/Library/Application Support/lazygit/config.yml"
    state: link
    force: true

