- name: lunarvim-from-github
  ansible.builtin.git:
    dest: "{{ home_dir }}/.config/nvim"
    repo: "git@github.com:lunarvim/lunarvim.git"
    version: 1.3.0
    update: true

- name: link-lunarvim-user-config
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/vim/lvim"
    dest: "{{ home_dir }}/.config/lvim"
    state: link
    force: true

- name: link-vimrc
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/vim/vimrc"
    dest: "{{ home_dir }}/.vimrc"
    state: link
