- name: astronvim-from-github
  ansible.builtin.git:
    dest: "{{ home_dir }}/.config/nvim"
    repo: "git@github.com:AstroNvim/AstroNvim.git"
    version: main
    update: true

- name: create-astronvim-user-dir
  ansible.builtin.file:
    state: directory
    path: "{{ home_dir }}/.config/nvim/lua/user/"
    recurse: true

- name: link-astronvim-user-config
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/vim/astronvim/init.lua"
    dest: "{{ home_dir }}/.config/nvim/lua/user/init.lua"
    state: link
    force: true

- name: link-vimrc
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/vim/vimrc"
    dest: "{{ home_dir }}/.vimrc"
    state: link
