- name: install-aws-mfa
  ansible.builtin.pip:
    executable: pip3
    name: aws-mfa

- name: check-node
  ansible.builtin.shell: "node -v"
  ignore_errors: true
  register: node_check

- name: install-node
  ansible.builtin.shell: "fnm install latest && fnm default latest"
  when: node_check.stderr.find('not available') != -1

- name: check-pnpm
  ansible.builtin.shell: "pnpm -v"
  ignore_errors: true
  register: pnpm_check

- name: install-pnpm
  ansible.builtin.shell: "npm i -g pnpm"
  when: pnpm_check.stderr.find('not available') != -1
