- name: install-aws-mfa
  ansible.builtin.pip:
    executable: pip3
    name: aws-mfa

- name: check-node
  ansible.builtin.shell: "node -v"
  ignore_errors: true
  register: node_check

- name: install-node
  ansible.builtin.shell: "volta install node@latest"
  when: node_check.stdout.find('not available') != -1

- name: check-yarn
  ansible.builtin.shell: "yarn -v"
  ignore_errors: true
  register: yarn_check

- name: install-yarn
  ansible.builtin.shell: "volta install yarn@latest"
  when: yarn_check.stdout.find('not available') != -1
    
