- name: link-lazygit-config
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/misc/lazygit.yml"
    dest: "{{ home_dir }}/Library/Application Support/lazygit/config.yml"
    state: link
    force: true

- name: link-lazygit-nvim-config
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/misc/lazygit-nvim.yml"
    dest: "{{ home_dir }}/Library/Application Support/lazygit/nvim.yml"
    state: link
    force: true

- name: link-lazydocker-config
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/misc/lazydocker.yml"
    dest: "{{ home_dir }}/Library/Application Support/lazydocker/config.yml"
    state: link
    force: true

- name: link-alacritty-config
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/misc/alacritty.yml"
    dest: "{{ home_dir }}/.alacritty.yml"
    state: link
    force: true

- name: link-alacritty-config
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/misc/iterm.json"
    dest: "{{ home_dir }}/Library/Application Support/iTerm2/DynamicProfiles/iterm.json"
    state: link
    force: true

- name: create-direnv-config-directory
  file:
    path: "{{ home_dir }}/.config/direnv"
    state: directory

- name: link-direnv-config
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/misc/direnv.toml"
    dest: "{{ home_dir }}/.config/direnv/direnv.toml"
    state: link
    force: true

- name: link-helix-config
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/helix"
    dest: "{{ home_dir }}/.config/helix"
    state: link
    force: true

# TODO: rectangle?!
