# TODO: rectangle?!
- name: link-tmux-config
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/misc/tmux.conf"
    dest: "{{ home_dir }}/.tmux.conf"
    state: link
    force: true

- name: link-lazygit-config
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/misc/lazygit.yml"
    dest: "{{ home_dir }}/Library/Application Support/lazygit/config.yml"
    state: link
    force: true

- name: link-lazygit-nvim-config
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/misc/lazygit-nvim.yml"
    dest: "{{ home_dir }}/Library/Application Support/lazygit/nvim.yml"
    state: link
    force: true

- name: link-lazydocker-config
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/misc/lazydocker.yml"
    dest: "{{ home_dir }}/Library/Application Support/lazydocker/config.yml"
    state: link
    force: true

- name: link-alacritty-config
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/alacritty/alacritty.toml"
    dest: "{{ home_dir }}/.config/alacritty/alacritty.toml"
    state: link
    force: true

- name: clone-alacritty-themes
  ansible.builtin.git:
    repo: https://github.com/alacritty/alacritty-theme
    dest: "{{ home_dir }}/.config/alacritty/themes"
    update: true

- name: install-scripts
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ home_dir }}/.local/bin/{{ item | basename | regex_replace('.sh$', '') }}"
    state: link
    force: true
  loop: "{{ query('ansible.builtin.fileglob', dotfiles_dir + '/scripts/*.sh', wantlist=True) }}"

- name: create-k9s-config-directory
  file:
    path: "{{ home_dir }}/Library/Application Support/k9s/skins"
    state: directory

- name: download-k9s-skin
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/derailed/k9s/master/skins/solarized-light.yaml
    dest: "{{ home_dir }}/Library/Application Support/k9s/skins/"
    force: true

- name: link-k9s-config
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/misc/k9s.yaml"
    dest: "{{ home_dir }}/Library/Application Support/k9s/config.yaml"
    state: link
    force: true

- name: create-docker-plugins-dir
  ansible.builtin.file:
    path: "{{ home_dir }}/.docker/cli-plugins"
    state: directory

- name: link-docker-compose-plugin
  ansible.builtin.file:
    src: "/opt/homebrew/bin/docker-compose"
    dest: "{{ home_dir }}/.docker/cli-plugins/docker-compose"
    state: link
    force: true

- name: link-docker-buildx-plugin
  ansible.builtin.file:
    src: "/opt/homebrew/bin/docker-buildx"
    dest: "{{ home_dir }}/.docker/cli-plugins/docker-buildx"
    state: link
    force: true
