- name: make-zed-config-dir
  ansible.builtin.file:
    path: "{{ home_dir }}/.config/zed"
    state: directory
    mode: 0755

- name: link-zed-settings
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/zed/settings.json"
    dest: "{{ home_dir }}/.config/zed/settings.json"
    state: link
    force: true

- name: link-zed-keymap
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/zed/keymap.json"
    dest: "{{ home_dir }}/.config/zed/keymap.json"
    state: link
    force: true
