# zsh being installed via homebrew leads to some directories used for autocomplete
# being considered insecure by zsh, this disables that check since we trust homebrew
export ZSH_DISABLE_COMPFIX=true
export EDITOR=nvim
export BAT_THEME="Solarized (light)"

alias tma="tmux a"
alias dc="docker compose"
alias tf="terraform"
alias k="kubectl"
alias eks="eksctl"
alias gdc="git diff --cached"
alias gds="git diff --stat"
alias ytop="ytop -c 'default-dark'"
alias lg="lazygit"
alias ld="lazydocker"
alias packersync="nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'"

function tm {
  rootdir=$(pwd)
  if [ ! -z "$1" ]; then
    rootdir=$(echo "$1" | sed 's:/*$::')
  fi
  session_name="${rootdir##*/}"
  if [ -z "$TMUX" ]; then
    tmux new -A -s $session_name -c $rootdir
  else
    tmux has-session -t $session_name
    if [ $? != 0 ]; then
      tmux new -A -c $rootdir -s $session_name -d
    fi
    tmux switch -t $session_name
  fi
}

function syncsys {
  cd $HOME/dotfiles
  git pull --rebase
  make
  cd -
}

function mdp() {
  # Requires Markdown Viewer extension
  # - https://chrome.google.com/webstore/detail/markdown-viewer/ckkdlimhmcjmikdlpkmbgfkaikojcbjk?hl=en
  open -a '/Applications/Google Chrome.app' $1
}

function gbrowse() {
  branch=$(git branch --show-current)
  if [ -z "$branch" ]; then
    branch=$(git rev-parse HEAD)
  fi
  gh browse --branch="$branch" $1
}

export HOMEBREW_BUNDLE_FILE="$HOME/dotfiles/Brewfile"

export VOLTA_HOME="$HOME/.volta"
export RUST_BIN="$HOME/.cargo/bin"
export PYENV_ROOT="$HOME/.pyenv"

export PATH="$VOLTA_HOME/bin:$PATH"
export PATH="$RUST_BIN:$PATH"
export PATH="$PYENV_ROOT/shims:$PATH"

export GOPATH="$HOME/go"
export PATH="$GOPATH/bin:$PATH"

#AWSume alias to source the AWSume script
alias awsume="source awsume"

#Auto-Complete function for AWSume
fpath=(~/.awsume/zsh-autocomplete/ $fpath)
. "$HOME/.cargo/env"
