# homebrew, load first because it manages many downstream dependencies from here
[ -f "/opt/homebrew/bin/brew" ] && eval "$(/opt/homebrew/bin/brew shellenv)"
[ -f "/home/linuxbrew/.linuxbrew/bin/brew" ] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# gpg
export GPG_TTY=$(tty)

#oh-my-zsh
plugins=(git vi-mode fzf direnv asdf)
ZSH_THEME="robbyrussell"
source $HOME/.oh-my-zsh/oh-my-zsh.sh

# 1password cli plugins
source /Users/sethetter/.config/op/plugins.sh
