# homebrew
[ -f "/opt/homebrew/bin/brew" ] && eval "$(/opt/homebrew/bin/brew shellenv)"

#oh-my-zsh
plugins=(git vi-mode fzf direnv)
ZSH_THEME="robbyrussell"
source $HOME/.oh-my-zsh/oh-my-zsh.sh

eval "$(rbenv init - zsh)"
eval "$(pyenv init -)"
eval "$(fnm env --use-on-cd)"

# pnpm
export PNPM_HOME="/Users/sethetter/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
