---
- hosts: all
  vars:
    home_dir: /Users/sethetter
    dotfiles_dir: "{{ home_dir }}/dotfiles"
  roles:
    - role: "./roles/zsh"
    - role: "./roles/git"
    - role: "./roles/vscode"
    - role: "./roles/misc"
