---
- hosts: all
  vars:
    home_dir: /Users/sethetter
    dotfiles_dir: "{{ home_dir }}/dotfiles"
    obsidian_dir: "{{ home_dir }}/obsidian"
  roles:
    - role: './roles/programs'
    - role: './roles/zsh'
    - role: './roles/tmux'
    - role: './roles/git'
    - role: './roles/nvim'
    - role: './roles/vscode'
    - role: './roles/obsidian'
    - role: './roles/alacritty'
